spring:
  datasource:
    url: jdbc:oracle:thin:@47.111.25.1:7777:orcl
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.Oracle10gDialect
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8